name: Tunnel with packetriot
version: 0.1.0
slug: packetriot
description: Permanent tunnel with packetriot
url: https://github.com/kvokka/home-assistant-addons
arch:
- armv7
- armhf
- amd64
- aarch64
startup: application
boot: auto
host_network: true
map: []
options:
  server_region: eu-central
  force_keygen: false
schema:
  server_region: "match(us-west|us-east|eu-central|asia-southeast|australia|us-south|asia-south|africa-south)"
  force_keygen: bool
