name: Tunnel with packetriot
version: 1.0.0
slug: packetriot
description: Permanent tunnel with packetriot
url: https://github.com/kvokka/home-assistant-addons
arch:
- armv7
- armhf
- amd64
- aarch64
startup: application
boot: auto
host_network: true
map: []
options:
  server_region: eu-central
  force_cleanup: false
  destination_server: homeassistant
  destination_port: 8123
schema:
  server_region: "match(us-west|us-east|eu-central|asia-southeast|australia|us-south|asia-south|africa-south)"
  force_cleanup: bool
  destination_server: str
  destination_port: int
